version: '3.7'

services:

    smtp4dev: # https://github.com/rnwood/smtp4dev/blob/master/docker-compose.yml
        image: rnwood/smtp4dev:linux-amd64-3.1.0-ci0856
        ports:
            - "3000:80"
            - "2525:25"
        volumes:
            - smtp4dev-data:/smtp4dev

volumes:
  smtp4dev-data:
